### ISSUE TITLE
[Proposal] Unifying note value and pitch: a new definition of Note and a few name changes

### ISSUE THREAD

**Issue by DJBen** [cemolcay/MusicTheory#16]
Music is the art of sounds flowing in time.

I find that `Note` has the semantic of pitch. The rhythm related representation `NoteValue`, however, is completely decoupled from the relatively heavily implemented pitch aspects of music theory. 

It is difficult for me to know from a single model which note to play and for how long. 

Here I propose a few changes:

- Rename `NoteType` to `Key`
> Rationale: note type is not descriptive name of the group of *relative* pitches. The term [key](https://en.wikipedia.org/wiki/Key_(music)) is used commonly instead.
> Because `Scale` is already in use and has different semantics, better not overload this name
- Rename `Note` to `Pitch`
> Rationale: pitch represents absolute frequency as the addition of octave number nails down the absolute frequency.
- Introduce new `Note`
    - Two properties`NoteValue` and `Pitch` to reflect both frequency and time it should occupy.
    - (optional) Have a extendable option set like if it has a staccato and / or if it exists as appoggiatura.
    - It is convenient for further usages, for example, the introduction of note group to describe a duplet consisting of two notes. Later we can group notes into bars, bars into sheet music.
    - Foundation to produce midi music.
- Added supports to `Note` in other classes
    - Tempo: add duration calculation for `Note`
    - etc.

### Compatibility
This change will **not** be compatible with the current `1.0` version. The version will be bumped to `2.0` per [semantic versioning](https://semver.org) requirement to indicate it is not backward compatible.

### Workflow
Accepting or not, I am making changes towards this goal in my own fork in order to glue my project together. I will label any related PR to this issue.

**Comment by cemolcay** [comment]
Renaming Note to Pitch makes sense. I also want to add enharmonics; sharp, double sharp, flat, double flat etc. instead of just flats. Do you have any suggestions for this as well?

**Comment by DJBen** [comment]
I propose adding [Accidental](https://en.wikipedia.org/wiki/Accidental_(music)) to `Pitch` (currently `Note`) like `NoteModifier` you used to modify `NoteValue`. Then adding the computed property `enharmonic` to `Pitch`. There might be better solutions.

There are microtonal notations such as half-tone flat and there might not exist enharmonics for them.

**Comment by cemolcay** [comment]
Hi @DJBen ,
I've been made a "major" progress towards your proposal as well as enharmonics.

So, I implemented an Accidental class with natural, flats and sharps.
https://github.com/cemolcay/MusicTheory/blob/enharmonics/Source/Accidental.swift

I ditched the `NoteType` and implemented a `Key` struct instead, with `KeyType` and `Accident` variables. 
https://github.com/cemolcay/MusicTheory/blob/enharmonics/Source/Key.swift

Also, renamed the `Note` to `Pitch`.
https://github.com/cemolcay/MusicTheory/blob/enharmonics/Source/Pitch.swift

Documentation is a mess right now, and I basically disabled the `Scale` and `Chord` structs and Tests, in order to work without handling their tons of errors. I'm going to update them accordingly, don't worry. Here's the accident and pitch tests:
https://github.com/cemolcay/MusicTheory/blob/e4d10ddf409cd2f4787f66661b44906dabee6a37/MusicTheoryTests/MusicTheoryTests.swift#L250

If you check it out and let me know if it makes sense, I'd be very happy. I probably release a new version with the changes in a couple of days.

**Comment by cemolcay** [comment]
OK, I updated all. You can now just checkout the enharmonics branch to see changes.

**Comment by DJBen** [comment]
Thank you! Will look!

**Comment by cemolcay** [comment]
Just released the v1.0.0 🎉
Looking forward to your contributions 🎹
